import { execFileSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { configDir, stateDir } from "../config/instance.js";
import type { NetworkEnv } from "../config/network-env.js";

export type Platform = "darwin" | "linux";

export function currentPlatform(): Platform | null {
  const p = process.platform;
  return p === "darwin" || p === "linux" ? p : null;
}

export function serviceLabel(instance: string): string {
  return `dev.herdr.slack.${instance}`;
}

export function unitPath(instance: string, platform: Platform, home = os.homedir()): string {
  return platform === "darwin"
    ? path.join(home, "Library", "LaunchAgents", `${serviceLabel(instance)}.plist`)
    : path.join(home, ".config", "systemd", "user", `herdr-slack@${instance}.service`);
}

/**
 * Path to the launcher the service unit points at.
 *
 * Deliberately inside the *config* dir, not HERDR_PLUGIN_ROOT: that root is a
 * herdr-managed GitHub checkout which herdr may replace or relocate on plugin
 * upgrade, which would silently break the service. The shim resolves the current
 * entrypoint at each launch instead of baking it in.
 */
export function shimPath(instance: string): string {
  return path.join(configDir(), `herdr-slack-${instance}`);
}

/** stateDir(instance) appends the instance key; the shim needs the base. */
function stateDirBase(): string {
  return path.dirname(stateDir("default"));
}

export function renderShim(
  nodePath: string,
  entrypoint: string,
  instance: string,
  dirs: { configDir: string; stateDir: string } = {
    configDir: configDir(),
    stateDir: stateDirBase(),
  },
  networkEnv: NetworkEnv = {},
): string {
  const exports = [
    `export HERDR_PLUGIN_CONFIG_DIR=${JSON.stringify(dirs.configDir)}`,
    `export HERDR_PLUGIN_STATE_DIR=${JSON.stringify(dirs.stateDir)}`,
    ...Object.entries(networkEnv).map(([key, value]) => `export ${key}=${JSON.stringify(value)}`),
  ].join("\n");
  return `#!/bin/sh
# Generated by 'herdr-slack setup'. Points the user service at the daemon
# without baking a herdr-managed path into the unit file — see ADR 0002.
# Config/state dirs are frozen here because launchd/systemd have no herdr env,
# and so is any override outbound HTTPS to Slack needed at setup time — a
# stripped service environment losing that is what ADR 0009 fixes.
${exports}
exec ${JSON.stringify(nodePath)} ${JSON.stringify(entrypoint)} daemon run --instance ${JSON.stringify(instance)}
`;
}

export function renderLaunchd(instance: string, shim: string): string {
  const label = serviceLabel(instance);
  const log = path.join(stateDir(instance), "daemon.log");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${label}</string>
  <key>ProgramArguments</key>
  <array><string>${shim}</string></array>
  <key>RunAtLoad</key><true/>
  <!-- Do not restart after a clean exit, so 'daemon stop' actually stops. -->
  <key>KeepAlive</key>
  <dict><key>SuccessfulExit</key><false/></dict>
  <key>StandardOutPath</key><string>${log}</string>
  <key>StandardErrorPath</key><string>${log}</string>
  <!-- Not "Background": that spawn type gets launchd's aggressive CPU/timer
       throttling (see 'launchctl print' -> "spawn type = background"), which
       coalesces the Slack Socket Mode ping/pong and idle-watchdog timers for
       minutes at a time on an otherwise-awake machine. "Standard" is the
       untouched, unthrottled tier a persistent websocket daemon needs. -->
  <key>ProcessType</key><string>Standard</string>
</dict>
</plist>
`;
}

export function renderSystemd(instance: string, shim: string): string {
  return `[Unit]
Description=herdr-slack bridge (${instance})
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${shim}
# on-failure, NOT always: 'always' restarts after a clean exit and would defeat
# 'daemon stop', which launchd's SuccessfulExit=false honours correctly. The two
# platforms must behave identically.
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
`;
}

export interface InstallResult {
  unit: string;
  shim: string;
  followUp: string[];
}

export function installService(
  instance: string,
  entrypoint: string,
  platform: Platform = currentPlatform() ?? "linux",
  nodePath = process.execPath,
  networkEnv: NetworkEnv = {},
  home = os.homedir(),
): InstallResult {
  const shim = shimPath(instance);
  mkdirSync(path.dirname(shim), { recursive: true, mode: 0o700 });
  writeFileSync(shim, renderShim(nodePath, entrypoint, instance, undefined, networkEnv), {
    mode: 0o700,
  });
  chmodSync(shim, 0o700);

  const unit = unitPath(instance, platform, home);
  mkdirSync(path.dirname(unit), { recursive: true });
  writeFileSync(
    unit,
    platform === "darwin" ? renderLaunchd(instance, shim) : renderSystemd(instance, shim),
    { mode: 0o644 },
  );

  const followUp =
    platform === "darwin"
      ? [`launchctl bootstrap gui/$(id -u) ${unit}`]
      : [
          "systemctl --user daemon-reload",
          `systemctl --user enable --now herdr-slack@${instance}.service`,
          // Without linger the service dies at logout, which defeats the point.
          "loginctl enable-linger $USER",
        ];

  return { unit, shim, followUp };
}

export interface EnableResult {
  ok: boolean;
  detail: string;
  /** Anything the user still has to do by hand. */
  followUp: string[];
}

/**
 * Load the unit so the daemon actually starts, rather than printing the
 * command and hoping.
 *
 * Setup used to install a unit file and then tell someone to run `launchctl
 * bootstrap` themselves — so a wizard that reported "Setup complete" left
 * nothing running, and `doctor` immediately said "service installed but not
 * loaded". The daemon *is* the app; installing it without starting it is an
 * unfinished job.
 *
 * `loginctl enable-linger` stays a follow-up on Linux: it can require
 * authentication, and failing that is not a reason to report setup as broken.
 */
export function enableService(
  instance: string,
  platform: Platform = currentPlatform() ?? "linux",
  home = os.homedir(),
): EnableResult {
  const unit = unitPath(instance, platform, home);
  try {
    if (platform === "darwin") {
      const domain = `gui/${process.getuid?.() ?? 0}`;
      // Bootout first so a re-run replaces a stale definition instead of
      // failing with "service already loaded" and leaving the old one live.
      try {
        execFileSync("launchctl", ["bootout", `${domain}/${serviceLabel(instance)}`], {
          stdio: "pipe",
        });
      } catch {
        // Not loaded yet — the normal first-install case.
      }
      execFileSync("launchctl", ["bootstrap", domain, unit], { stdio: "pipe" });
      return { ok: true, detail: `loaded ${serviceLabel(instance)}`, followUp: [] };
    }

    execFileSync("systemctl", ["--user", "daemon-reload"], { stdio: "pipe" });
    execFileSync("systemctl", ["--user", "enable", "--now", `herdr-slack@${instance}.service`], {
      stdio: "pipe",
    });
    return {
      ok: true,
      detail: `enabled herdr-slack@${instance}.service`,
      // Without linger the service dies at logout, which defeats the point.
      followUp: ["loginctl enable-linger $USER"],
    };
  } catch (error) {
    const detail =
      error instanceof Error ? (error.message.split("\n")[0] ?? error.message) : String(error);
    return {
      ok: false,
      detail,
      followUp:
        platform === "darwin"
          ? [`launchctl bootstrap gui/$(id -u) ${unit}`]
          : [
              "systemctl --user daemon-reload",
              `systemctl --user enable --now herdr-slack@${instance}.service`,
              "loginctl enable-linger $USER",
            ],
    };
  }
}

/**
 * Unregister the unit from launchd/systemd.
 *
 * Deleting the plist is not the same as unloading it: launchd keeps the job
 * definition registered until it is booted out, so a "reset" install left a
 * live job pointing at a shim that no longer exists — and one non-zero exit
 * away from launchd trying to run it. systemd has the same shape.
 *
 * Best-effort by design: a job that was never loaded reports an error, and
 * that is the normal case rather than a problem.
 */
export function disableService(
  instance: string,
  platform: Platform = currentPlatform() ?? "linux",
): { ok: boolean; detail: string } {
  try {
    if (platform === "darwin") {
      execFileSync(
        "launchctl",
        ["bootout", `gui/${process.getuid?.() ?? 0}/${serviceLabel(instance)}`],
        { stdio: "pipe" },
      );
      return { ok: true, detail: `booted out ${serviceLabel(instance)}` };
    }
    execFileSync("systemctl", ["--user", "disable", "--now", `herdr-slack@${instance}.service`], {
      stdio: "pipe",
    });
    return { ok: true, detail: `disabled herdr-slack@${instance}.service` };
  } catch (error) {
    const detail = error instanceof Error ? (error.message.split("\n")[0] ?? "") : String(error);
    return { ok: false, detail };
  }
}

export function uninstallService(
  instance: string,
  platform: Platform = currentPlatform() ?? "linux",
  home = os.homedir(),
): void {
  // Unregister before deleting the files the unit points at.
  disableService(instance, platform);
  rmSync(unitPath(instance, platform, home), { force: true });
  rmSync(shimPath(instance), { force: true });
}

export interface ServiceStatus {
  installed: boolean;
  loaded: boolean;
  /** The unit's target exists and is executable. */
  targetOk: boolean;
  unit: string;
  detail?: string;
  /**
   * pid launchd is currently running for this job, darwin only.
   *
   * Absent means "not currently running under launchd" — which is different
   * from `loaded`: a job can be loaded (registered) but not running because
   * something else already holds the daemon lock. That something else is
   * usually herdr's own `daemon ensure` startup-hook fallback, which has no
   * crash recovery at all — seen live losing the race after every reboot and
   * running unsupervised for days before a crash finally killed it outright.
   */
  runningPid?: number;
}

/** `launchctl print` only has a `pid = N` line while the job is actively running. */
export function parseLaunchctlPid(output: string): number | undefined {
  const match = output.match(/^\s*pid = (\d+)/m);
  return match?.[1] ? Number(match[1]) : undefined;
}

/**
 * Report on the installed unit.
 *
 * `targetOk` is checked separately from `loaded` on purpose: a plugin upgrade
 * that moves the checkout leaves a perfectly loaded unit pointing at nothing,
 * and "installed and enabled" would otherwise look healthy while the daemon
 * never starts again.
 */
export function serviceStatus(
  instance: string,
  platform: Platform = currentPlatform() ?? "linux",
  home = os.homedir(),
): ServiceStatus {
  const unit = unitPath(instance, platform, home);
  const installed = existsSync(unit);
  if (!installed) return { installed: false, loaded: false, targetOk: false, unit };

  const shim = shimPath(instance);
  let targetOk = existsSync(shim);
  if (targetOk) {
    // The shim may exist but point at an entrypoint that moved.
    const body = readFileSync(shim, "utf8");
    const match = body.match(/exec\s+"([^"]+)"\s+"([^"]+)"/);
    const entry = match?.[2];
    if (entry && !existsSync(entry)) targetOk = false;
  }

  let loaded = false;
  let runningPid: number | undefined;
  let detail: string | undefined;
  try {
    if (platform === "darwin") {
      const out = execFileSync(
        "launchctl",
        ["print", `gui/${process.getuid?.() ?? 0}/${serviceLabel(instance)}`],
        {
          stdio: "pipe",
        },
      ).toString();
      loaded = true;
      runningPid = parseLaunchctlPid(out);
    } else {
      const out = execFileSync(
        "systemctl",
        ["--user", "is-enabled", `herdr-slack@${instance}.service`],
        {
          stdio: "pipe",
        },
      ).toString();
      loaded = out.trim() === "enabled";
    }
  } catch (error) {
    detail = error instanceof Error ? error.message.split("\n")[0] : String(error);
  }

  return {
    installed,
    loaded,
    targetOk,
    unit,
    ...(detail === undefined ? {} : { detail }),
    ...(runningPid === undefined ? {} : { runningPid }),
  };
}
